# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93742efaca5353f7abc3ef13678aa3a5040d4b35767da9020ca74b32713aa1bf2098f2126325f9c4bab95a3604e50c7d216d705ca567e8587262434ed70792f

test:
  secret_key_base: a8ef3918e0bfbc2d83a02c5bc24c06eaeed08fd96d523e24ea78868f35dfe5aaa5f9e75539a75cda21223587e25bd704ea323d93fd0f268b977c0e4d9c79b1be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
